displayName=Collection Log Popup Enhanced
author=SnakeSteak
description=Displays a popup and sound effects on new collection logs
tags=collection log,clog,c-log,popup,notification
version=1.32
plugins=com.snakesteak.collectionlogpopupenhanced.CollectionLogPopupEnhancedPlugin
build=standard
